config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

  resources :profile, except: [:show]

  get 'demo' => 'demo#show'
  get 'demo/:user_id' => 'demo#get_profiles'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthConcern

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/concerns/auth_concern.rb
module AuthConcern
  extend ActiveSupport::Concern

  def authenticate_user! (dest=new_user_session_path)
    redirect_to dest if !current_user
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  before_action -> { authenticate_user! }

	def show
    render
	end

	def get_profiles
		@profiles = Profile.where(user_id: current_user.id, availability: 'online').to_a
		render :json => { profiles: @profiles }
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action -> { authenticate_user! }

	def index
		@profiles = Profile.where(user_id: current_user.id).to_a

		@online_profiles = Profile.where(user_id: current_user.id, availability: 'online').to_a
		render
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action -> { authenticate_user! }
  before_action :get_profile, except: [:new, :create, :index]

  def index
    @profiles = Profile.where(user_id: params[:format]).to_a
	end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create(profile_params)
    if @profile.save
      @profile.update_attribute(:user_id, current_user.id)
      redirect_to root_path, notice: "Successfully update profile"
    else
      render :new, alert: 'Failed to create new profile'
    end
  end

	def edit
    render
	end

  def update
    if @profile.update(profile_params)
      redirect_to root_path, notice: "Successfully update profile"
    else
      redirect_to edit_profile_path(@profile.id), alert: "Failed update profile"
    end
  end

  def destroy
    if @profile.destroy
      redirect_to root_path, notice: "Successfully destroy profile"
    else
      render root_path, alert: "Failed to destroy profile"
    end
  end

  protected

  def get_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params
      .require(:profile)
      .permit(
        :name,
        :role,
        :phone,
        :availability
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/demo/_msg_button.html.erb
<div class="demo">
  <button class="btn btn-primary btn-demo" onClick="showPopup()">
  <i class="fa-brands fa-whatsapp"></i>
  </button>
  <div class="popup" id="popup-demo" style="display: none;">
  <div class="popup-header">
    <div>Who's Online?</div>
    <div class="btn-close" onClick="hidePopup()">
      <i class="fas fa-close"></i>
    </div>
  </div>
  <div class="popup-body" id="profile-list">
  </div>
  </div>
</div>

<style>
  .demo {
    position: relative;
  }
  .popup {
    background-color: #fff;
    min-width: 250px;
    min-height: 120px;
    position: absolute;
    bottom: 48px;
    right: 288px;
    border-radius: 10px;
    padding: 16px;
    box-shadow: 2px 2px 15px 2px rgb(0 0 0 / 17%);
    margin-bottom: 24px;
  }
  .popup-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 16px;
  }
  .profile {
    display: flex;
    column-gap: 8px;
    cursor: pointer;
    margin-bottom: 8px;
  }
  .profile-body {
    text-align: left;
  }
  .btn-close {
    cursor: pointer;
  }
  .btn-demo {
    width: 52px;
    height: 52px;
    border-radius: 50% !important;
    font-size: 24px;
    margin: auto;
    justify-content: center;
    align-items: center;
    display: flex;
    cursor: pointer;
  }
  .avatar {
    background: #6777ef;
    border-radius: 50%;
    color: #e3eaef;
    display: inline-block;
    font-size: 16px;
    font-weight: 300;
    margin: 0;
    position: relative;
    vertical-align: middle;
    line-height: 1.28;
    height: 45px;
    width: 45px;
  }
  .text-white {
    color: #fff !important;
  }
  .status {
    color: #63ed7a;
    font-size: 14px;
  }
</style>

<script type="text/javascript">
  fetch('http://localhost:3000/demo/3')
   .then(resp => resp.json())
   .then(json => {
    const data = json.profiles
    let profile;
    for(var i in data)
      profile = data[i]
       var item = document.createElement('div');
        item.innerHTML =
          '<a class="profile" href="https://wa.me/' + profile.phone + '"><figure class="avatar text-white" data-initial="' + profile.name.split(' ').map((v) => v[0]).join('').toUpperCase() + '"></figure>' +
          '<div class="profile-body"><div>' + profile.name + '</div>' +
          '<div class="status"><i class="fas fa-circle"></i> ' + profile.availability + '</div></div></a>';
        document.getElementById("profile-list").appendChild(item);
    }
  )

  function showPopup() {
    var popup = document.getElementById('popup-demo')
    console.log(popup)
    popup.style.display = 'block'
  }
  function hidePopup() {
    var popup = document.getElementById('popup-demo')
    console.log(popup)
    popup.style.display = 'none'
  }
</script>

app/views/demo/show.html.erb
<section class="section">
  <div class="container mt-5">
    <div class="page-error">
      <div class="page-inner">
        <h1>Demo</h1>
        <div class="page-description">
          Try click Whatsapp button.
        </div>
        <div class="page-search">
          <%= render 'demo/msg_button' %>
          <div class="mt-3">
            <a href="/">Back to Home</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<section class="section">
  <div class="section-header">
    <h1>Dashboard</h1>
  </div>

  <div class="card-wrapper">
    <div class="card">
      <div class="card-body">
        <h4>Total Profile: <%= @profiles.count %></h4>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h4>Online: <%= @online_profiles.count %></h4>
      </div>
    </div>
  </div>

  <div class="card card-primary">
    <div class="card-body">
      <h4>Chat with website visitors via Whatsapp</h4>
      <%= link_to 'Demo', demo_path, class: 'btn btn-primary' %>
    </div>
  </div>
</section>

app/views/layouts/_navigation.html.erb
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <div class="navbar-custom">
    <figure class="avatar mr-2 avatar-sm bg-info text-white" data-initial="<%= current_user.name.split(' ').collect { |s| s[0] }.join('') %>"></figure>
    <%= link_to "Hi, #{current_user.name}", edit_user_registration_path, class: 'nav-link-custom' %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link-custom btn btn-dark' %>
  </div>
  <div class="main-sidebar"> 
    <!-- sidebar wrapper -->
    <aside id="sidebar-wrapper">
      <!-- sidebar brand -->
      <div class="sidebar-brand">
        <a href="/">Contact Support</a>
      </div>
      <!-- sidebar menu -->
      <ul class="sidebar-menu">
        <!-- menu header -->
        <li class="menu-header">Dashboard</li>
        <!-- menu item -->
        <li>
          <a href="/"><i class="fas fa-house"></i><span>Dashboard</span></a>
        </li>
        <li class="menu-header">Profile</li>
        <li>
          <%= link_to new_profile_path(current_user.id) do %>
            <i class="fas fa-user-plus"></i><span>Create New</span>
          <% end %>
        </li>
        <li>
          <%= link_to profile_index_path(current_user.id) do %>
            <i class="fas fa-users"></i><span>Index</span>
          <% end %>
        </li>
      </ul>
    </aside>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact Support</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", 'media': 'all' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="app">
      <div class="main-wrapper main-wrapper-1">
        <% if request.path == '/demo' %>
          <%= yield %>
        <% elsif current_user.present? %>
          <%= render 'layouts/navigation' %>
          <div class="main-content">
            <%= yield %>
          </div>
        <% else %>
          <section class="section">
            <div class="wrapper">
              <div class="login-brand">
                <h1>Contact Support</h1>
              </div>

              <%= yield %>
            </div>
          </section>
        <% end %>
        <footer class="simple-footer">
          Copyright © 2023 <div class="bullet"></div> Contact Support
        </footer>
      </div>
    </div>
  </body>
</html>